### ISSUE TITLE
Bug: URL property is not visible on kanban cards

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#1331]
**Steps to reproduce the behavior:**
1. Create new board
2. Create new card
3. Add URL property to the card and close card dialog
4. Make URL property visible on the cards via _Properties_ menu
5. URL property is not visible on the kanban card

**Expected behavior:**
URL property should be visible on the kanban card

**Screenshots:**
URL property in the card dialog:
![image](https://user-images.githubusercontent.com/5587620/134761569-d0a2b0f4-6ef3-442c-b602-e0399512350d.png)

URL property on the kanban card:
![image](https://user-images.githubusercontent.com/5587620/134761644-a9e415fb-42b3-47af-afe9-d9ff5047ed04.png)

**Edition and Platform:**
 - Edition: Personal Server
 - Version: v0.9.1
 - Browser and OS: Chrome 93 on Windows

**Additional context:**
Regression was introduced in #1160

**Comment by kamre** [comment]
Originally there was this rule in `kanbanCard.scss`:
```scss
.KanbanCard {
    ...
    > .octo-propertyvalue {
        margin: 4px 0 0;
        font-size: 12px;
        line-height: 18px;

        &:empty {
            display: none;
        }
    }
    ...
}
```
and it didn't work because we have the following structure in the DOM:
![image](https://user-images.githubusercontent.com/5587620/134761907-ede156af-1ed5-4494-9cbb-752f2163d90c.png)
and immediate children (`>` in CSS selector) don't have `octo-propertyvalue` class.

So after removing `>` there is `&:empty` selector that is always used for `input` elements because they can't have any children.

One possible fix is just to remove this rule. @asaadmahmood what do you think about this?
