### ISSUE TITLE
Can't connect to focalboard docker container, but no error messages

### ISSUE THREAD

**Issue by panomitrius** [mattermost/focalboard#2372]
I just started up a docker container of Focalboard. At first it worked great. 

But then I wanted to edit the config.json so I took it down and restarted it with a mounted config.json file. However it then stopped working (I can't connect to the container anymore) even when trying to revert to the initial settings and deleting all data. I'm not getting any error messages.

I then tried with the postgres setup. But same thing, no error messages but unable to connect. In my nginx reverse proxy log I get Connection reset by peer error messages. I've also tried lynx localhost:3535, but not working either. Tried a ssh tunnel, not working.

The log of my current setup with postgres as db:

```
root@myserver:/var/docker/focalboard# docker-compose up 
Starting focalboard-db ... done
Starting focalboard-app ... done
Attaching to focalboard-db, focalboard-app
focalboard-db    | 
focalboard-db    | PostgreSQL Database directory appears to contain a database; Skipping initialization
focalboard-db    | 
focalboard-db    | 2022-02-22 21:09:56.531 UTC [1] LOG:  starting PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
focalboard-db    | 2022-02-22 21:09:56.534 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
focalboard-db    | 2022-02-22 21:09:56.534 UTC [1] LOG:  listening on IPv6 address "::", port 5432
focalboard-db    | 2022-02-22 21:09:56.538 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
focalboard-db    | 2022-02-22 21:09:56.543 UTC [28] LOG:  database system was shut down at 2022-02-22 21:09:51 UTC
focalboard-db    | 2022-02-22 21:09:56.554 UTC [1] LOG:  database system is ready to accept connections
focalboard-app   | 2022/02/22 21:09:56 readConfigFile
focalboard-app   | 2022/02/22 21:09:56 {ServerRoot:http://localhost:8000 Port:8000 DBType:postgres DBConfigString:postgres://admin:somepassword@focalboard-db/boards?sslmode=disable&connect_timeout=10 DBTablePrefix: UseSSL:false SecureCookie:false WebPath:./pack FilesDriver:local FilesS3Config:{AccessKeyID: SecretAccessKey: Bucket: PathPrefix: Region: Endpoint: SSL:false SignV2:false SSE:false Trace:false} FilesPath:/data/files Telemetry:true TelemetryID: PrometheusAddress::9092 WebhookUpdate:[] Secret: SessionExpireTime:2592000 SessionRefreshTime:18000 LocalOnly:false EnableLocalMode:true LocalModeSocketLocation:/var/tmp/focalboard_local.socket EnablePublicSharedBoards:false FeatureFlags:map[] AuthMode:native LoggingCfgFile: LoggingCfgJSON: AuditCfgFile: AuditCfgJSON: NotifyFreqCardSeconds:0 NotifyFreqBoardSeconds:0}
focalboard-app   | info  [2022-02-22 21:09:56.894 Z] FocalBoard Server                        caller="main/main.go:56" version=0.15.0 edition=linux build_number=dev build_date=n/a build_hash=8d94422d5f7e61a922f11f9ba761843e39006dd8
focalboard-app   | info  [2022-02-22 21:09:56.909 Z] connectDatabase                          caller="sqlstore/sqlstore.go:40" dbType=postgres
focalboard-app   | info  [2022-02-22 21:09:56.926 Z] Initialized notification backend         caller="notify/service.go:64" name=notifyLogger
focalboard-app   | debug [2022-02-22 21:09:56.930 Z] Fetched template blocks                  caller="app/templates.go:29" count=7
focalboard-app   | debug [2022-02-22 21:09:56.930 Z] Template import not needed, skipping     caller="app/templates.go:33"
focalboard-app   | info  [2022-02-22 21:09:56.932 Z] Server.Start                             caller="server/server.go:247"
focalboard-app   | info  [2022-02-22 21:09:56.932 Z] http server started                      caller="web/webserver.go:118" port=8000
focalboard-app   | info  [2022-02-22 21:09:56.933 Z] Starting unix socket server              caller="server/server.go:394"
```

The docker-compose.yml is looking like this:
```
version: '3.3'
services:
    focalboard:
        image: mattermost/focalboard:latest
        container_name: focalboard-app
        restart: unless-stopped
        depends_on:
          - focalboard-db
        ports:
            - '3535:8000'
        volumes:
           - './data:/data'
           - '/var/docker/focalboard/focalboard_conf/config.json:/opt/focalboard/config.json:rw'
    focalboard-db:
      image: postgres:latest
      container_name: focalboard-db
      restart: unless-stopped
      volumes:
        - "./postgres_data:/var/lib/postgresql/data"
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: somepassword
        POSTGRES_DB: boards  
```

The config.json like this
```

{
  "serverRoot": "http://localhost:8000",
  "port": 8000,
  "dbtype": "postgres",
  "dbconfig": "postgres://admin:somepassword@focalboard-db/boards?sslmode=disable&connect_timeout=10",
  "postgres_dbconfig": "dbname=boards sslmode=disable",
  "useSSL": false,
  "webpath": "./pack",
  "filespath": "/data/files",
  "telemetry": true,
  "prometheus_address": ":9092",
  "session_expire_time": 2592000,
  "session_refresh_time": 18000,
  "localOnly": false,
  "enableLocalMode": true,
  "localModeSocketLocation": "/var/tmp/focalboard_local.socket"
}
```

docker ps shows this:
```
CONTAINER ID   IMAGE                              COMMAND                  CREATED          STATUS                  PORTS                                                                                                                                                                                           NAMES
d420817a8ed5   mattermost/focalboard:latest       "/opt/focalboard/bin…"   16 minutes ago   Up 10 minutes           9092/tcp, 0.0.0.0:3535->8000/tcp, :::3535->8000/tcp                                                                                                                                             focalboard-app
b4b860d45c3e   postgres:latest                    "docker-entrypoint.s…"   16 minutes ago   Up 10 minutes           5432/tcp                                                                                                                                                                                        focalboard-db
```

The first docker-compose that actually worked was looking like this:

```
version: '3.3'
services:
    focalboard:
        volumes:
            - './data:/data'
        ports:
            - '3535:8000'
        image: mattermost/focalboard:latest
        container_name: focalboard
```

Any ideas what could be the issue? 

(All my other containers with nginx reverse proxys are working as usual)
