### ISSUE TITLE
Bug: Unable to register when running behind traefik reverse proxy with any middleware.

### ISSUE THREAD

**Issue by laundmo** [mattermost/focalboard#243]
**Summary:**
I'm running Focalboard in docker behind the Traefik2 Reverse Proxy that has some middlewares set up. When trying to register I'm presented with an "Invalid registration link, please contact your administrator" error. There are no log messages written.

The curious part is, that *any* Traefik2 middleware seems to cause this issue, but leaving them out works. I've tested with a Ratelimit middleware, a Headers middleware that just inserts a same-origin referrer policy and a basic-auth middleware. All of them cause the same issue, which makes a configuration mistake on my side very unlikely.

**Steps to reproduce the behaviour:**
1. clone the repo
2. add traefik labels to docker-compose config (full configs below)
3. add db and app containers to network (full configs below)
4. docker-compose build and up
5. go to the domain configured in traefik
6. try to create a account

**Expected behaviour:**
Being able to create a account.

**Platform:**
 - Browser and version: Firefox 87.0
 - OS and version: Server: Ubuntu 20.04 LTS, Client: Windows 10

**Additional context:**
<details><summary>docker-compose.yml</summary>
<p>

Docker compose with added networks and Traefik2 labels.

```yaml
version: "3"
services:
  app:
    build:
      context: ./
    container_name: focalboard
    depends_on:
      - focalboard-db
    environment:
      - VIRTUAL_HOST=focalboard.local
      - VIRTUAL_PORT=8000
    volumes:
      - "./config.json:/opt/focalboard/config.json"
    networks:
      - internal
      - t2_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=t2_proxy"
      ## HTTP Routers
      - "traefik.http.routers.focalboard-rtr.entrypoints=https"
      - "traefik.http.routers.focalboard-rtr.rule=Host(`focalboard.domain.com`)" 
      - "traefik.http.routers.focalboard-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.focalboard-rtr.middlewares=focal-test-chain@file"
      ## HTTP Services
      - "traefik.http.routers.focalboard-rtr.service=focalboard-svc"
      - "traefik.http.services.focalboard-svc.loadbalancer.server.port=8000"

  focalboard-db:
    image: postgres:latest
    container_name: focalboard-postgres
    restart: always
    volumes:
      - "./data:/var/lib/postgresql/data"
    networks:
      - internal
    environment:
      POSTGRES_DB: boards
      POSTGRES_USER: boardsuser
      POSTGRES_PASSWORD: boardsuser-password

networks:
  internal:
  t2_proxy:
    external:
      name: t2_proxy
```

</p>
</details>

<details><summary>traefik2 ratelimit middleware</summary>
<p>

Traefik2 middleware config used

```toml

[http.middlewares]
  [http.middlewares.middlewares-rate-limit]
    [http.middlewares.middlewares-rate-limit.rateLimit]
      average = 100
      burst = 50

  [http.middlewares.focal-test-chain]
    [http.middlewares.focal-test-chain.chain]
      middlewares = [ "middlewares-rate-limit" ]
````

</p>
</details>

<details><summary>Request HAR json</summary>
<p>

This is the HAR from the request that is sent when i click the register button. Domains have been replaced with domain.com and IPs with 0.0.0.0. The error occurs whether or not i enter anything in the form, here i've left it empty.

```json
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "Firefox",
      "version": "87.0"
    },
    "browser": {
      "name": "Firefox",
      "version": "87.0"
    },
    "pages": [
      {
        "startedDateTime": "2021-04-11T19:20:33.089+02:00",
        "id": "page_4",
        "title": "Focalboard",
        "pageTimings": {
          "onContentLoad": -1,
          "onLoad": -1
        }
      }
    ],
    "entries": [
      {
        "pageref": "page_4",
        "startedDateTime": "2021-04-11T19:20:33.089+02:00",
        "request": {
          "bodySize": 51,
          "method": "POST",
          "url": "https://focalboard.domain.com/api/v1/register",
          "httpVersion": "HTTP/2",
          "headers": [
            {
              "name": "Host",
              "value": "focalboard.domain.com"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0"
            },
            {
              "name": "Accept",
              "value": "application/json"
            },
            {
              "name": "Accept-Language",
              "value": "en-GB,en;q=0.5"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "Referer",
              "value": "https://focalboard.domain.com/register"
            },
            {
              "name": "Content-Type",
              "value": "application/json"
            },
            {
              "name": "Authorization",
              "value": ""
            },
            {
              "name": "X-Requested-With",
              "value": "XMLHttpRequest"
            },
            {
              "name": "Origin",
              "value": "https://focalboard.domain.com"
            },
            {
              "name": "Content-Length",
              "value": "51"
            },
            {
              "name": "DNT",
              "value": "1"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Pragma",
              "value": "no-cache"
            },
            {
              "name": "Cache-Control",
              "value": "no-cache"
            },
            {
              "name": "TE",
              "value": "Trailers"
            }
          ],
          "cookies": [],
          "queryString": [],
          "headersSize": 522,
          "postData": {
            "mimeType": "application/json",
            "params": [],
            "text": "{\"email\":\"\",\"username\":\"\",\"password\":\"\",\"token\":\"\"}"
          }
        },
        "response": {
          "status": 401,
          "statusText": "Unauthorized",
          "httpVersion": "HTTP/2",
          "headers": [
            {
              "name": "content-type",
              "value": "application/json"
            },
            {
              "name": "date",
              "value": "Sun, 11 Apr 2021 17:20:02 GMT"
            },
            {
              "name": "content-length",
              "value": "12"
            },
            {
              "name": "X-Firefox-Spdy",
              "value": "h2"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "application/json",
            "size": 12,
            "text": "{\"error\":\"\"}"
          },
          "redirectURL": "",
          "headersSize": 136,
          "bodySize": 148
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": 0,
          "connect": 0,
          "ssl": 0,
          "send": 1,
          "wait": 26,
          "receive": 1
        },
        "time": 28,
        "_securityState": "secure",
        "serverIPAddress": "0.0.0.0",
        "connection": "443"
      }
    ]
  }
}
```
</p>
</details>
