### ISSUE TITLE
Bug: focalboard cant start with docker-compose and mysql database

### ISSUE THREAD

**Issue by phillipunzen** [mattermost/focalboard#2732]
## Steps to reproduce the behavior

1. Put the following code in the **docker-compose.yml**
```
version: '3.8'

networks:
  traefik:
    external: true
  mdb:
    external: true

services:
  focalboard:
     restart: always
     container_name: focalboard
     networks:
       - mdb
       - traefik
     image: mattermost/focalboard:latest
     volumes:
      - ./config.json:/opt/focalboard/config.json
     labels:
       - "traefik.enable=true"
       - "traefik.http.routers.focalboard.entrypoints=http"
       - "traefik.http.routers.focalboard.rule=Host(DOMAIN)"
       - "traefik.http.middlewares.focalboard-https-redirect.redirectscheme.scheme=https"
       - "traefik.http.routers.focalboard.middlewares=focalboard-https-redirect"
       - "traefik.http.routers.focalboard-secure.entrypoints=https"
       - "traefik.http.routers.focalboard-secure.rule=Host(DOMAIN)"
       - "traefik.http.routers.focalboard-secure.tls=true"
       - "traefik.http.routers.focalboard-secure.tls.certresolver=http"
       - "traefik.http.routers.focalboard-secure.service=focalboard"
       - "traefik.http.services.focalboard.loadbalancer.server.port=8000"
       - "traefik.docker.network=traefik"
       - "traefik.http.routers.focalboard-secure.middlewares=secHeaders@file"
       - "com.centurylinklabs.watchtower.enable=true"
```
 
2. Put the following code in the **config.json**
```
{
  "serverRoot": "http://localhost:8000",
  "port": 8000,
  "dbtype": "mysql",
  "dbconfig": "USER:PASSWORD@tcp(DB-HOST:3306)/DATABASE",
  "useSSL": false,
  "webpath": "./pack",
  "filespath": "/data/files",
  "telemetry": true,
  "session_expire_time": 2592000,
  "session_refresh_time": 18000,
  "localOnly": false,
  "enableLocalMode": true,
  "localModeSocketLocation": "/var/tmp/focalboard_local.socket"
}
```

3. Start the docker-container
`docker-compose up -d`
## Expected behavior

I Want to create a docker-compose app to start focalboard behind traefik. Focalboard created the SQL Tables, but one missing him.

Error Message:
`error [2022-04-06 07:05:14.151 Z] Table creation / migration failed        caller="sqlstore/sqlstore.go:54" error="driver: mysql, message: failed when applying migration, command: apply_migration, originalError: Error 1146: Table 'DATABASE.workspaces' doesn't exist, query:`

focalboard created following tables:
```
- blocks
- blocks_history
- db_lock
- notification_hints
- schema_migrations
- sessions
- subscriptions
- system_settings
- teams
- users
```

I tried this way five times, it is the same result.

## Edition and Platform

 - Edition: Personal Server
 - Version: Latest Docker Image
 - Browser and OS: Chrome on Windows and Firefox on Debian 11

## Additional context (optional)

The Application can't start. The Container is in the "Restarting" State.
