### ISSUE TITLE
Bug: k8s - cannot parse 'port' as int: strconv.ParseInt:

### ISSUE THREAD

**Issue by kissi7** [mattermost/focalboard#363]
**Summary:**
There is a problem to run focalboard in the kubernetes. Issue to parse the port. Like some kubernetes variable cause the issue.

**Steps to reproduce the behavior:**
Run in any kubernetes cluster:
kubectl run --rm -i --tty focalboard --image=mattermost/focalboard --restart=Never

**Expected behavior:**
focalboard will start as it can pass the port from the config file and should by immune for any other k8s env variables.
It should simply start as it does by running "docker run -it --rm mattermost/focalboard"

**ERROR LOG:**
2021/04/30 07:16:14 Focalboard Server 
2021/04/30 07:16:14 Version: 0.6.6 
2021/04/30 07:16:14 Edition: linux 
2021/04/30 07:16:14 Build Number: dev 
2021/04/30 07:16:14 Build Date: Thu Apr 29 19:28:50 UTC 2021 
2021/04/30 07:16:14 Build Hash: d09d6e0e4080b257e3d0a898cb1cab4d2640efb7 
2021/04/30 07:16:14 Unable to read the config file: 1 error(s) decoding: 
 
* cannot parse 'port' as int: strconv.ParseInt: parsing "tcp://10.43.228.108:8000": invalid syntax 

**Platform:**
 - OS and version: kubernetes cluster v1.20.4

**Comment by kissi7** [comment]
Hi, no I did not specify this port. `config.json` is not touched at all. I found the root cause.
If you deploy focalboard in the kubernetes and expose port 8000 and deployment name is "focalboard" than kuberneted create various env variables and one of them is "FOCALBOARD_PORT=tcp://10.43.228.108:8000" This is k8s native format.
The focalboard should be able to handle this if you plane to run it in the kubernetes in the future too.

**Comment by geekgonecrazy** [comment]
You can add: `enableServiceLinks: false` to the pod template spec to get around this.

**Comment by fabricecolas** [comment]
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: focalboard
  namespace: your-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: focalboard
  template:
    metadata:
      labels:
        app: focalboard
    spec:
      enableServiceLinks: false # << ----------- HERE
      containers:
        - name: focalboard
          image: mattermost/focalboard:latest
[...]
---
```
( thanks @geekgonecrazy )
