### ISSUE TITLE
Bug: Sidebar menu items jittering

### ISSUE THREAD

**Issue by johncadengo** [mattermost/focalboard#4644]
## Steps to reproduce the behavior

1. Log in to dashboard
2. Second user logs into dashboard

## Expected behavior

I expect to be able to see the sidebar menu items

## Screenshots (optional)

https://user-images.githubusercontent.com/561587/225161299-1b7404c2-730d-4fa4-99c3-4cf498832cf8.mov

## Edition and Platform

 - Edition: Personal Server
 - Version: v7.8.0
 - Browser and OS: Tried multiple browsers (Chrome, Firefox, Safari, on Macs)

## Additional context (optional)

When the other users log out, it stops occurring. If only one user is logged in and viewing the page, it's fine. When multiple users are viewing the page, this occurs.

We are on a personal server, using Docker.

**Comment by johncadengo** [comment]
This is what the inspector console looks like on Safari.

https://user-images.githubusercontent.com/561587/225161874-904517c4-a454-4903-8f62-ed1515f470c6.mov

The line of code:

<img width="1435" alt="Screen Shot 2023-03-14 at 4 08 35 PM" src="https://user-images.githubusercontent.com/561587/225161989-a6d6bcca-76f7-4814-873d-20a5698b40fc.png">

**Comment by johncadengo** [comment]
The docker compose yaml is very simple:

```
version: "3"
services:
  app:
    image: mattermost/focalboard:latest
    container_name: focalboard
    volumes:
      - fbdata:/opt/focalboard/data
    ports:
      - 8000:8000
    environment:
      - VIRTUAL_HOST=focalboard.local
      - VIRTUAL_PORT=8000
    restart: always

volumes:
  fbdata:
```
