### ISSUE TITLE
Bug: Upgrade failed (readonly database)

### ISSUE THREAD

**Issue by loranger** [mattermost/focalboard#735]
**Summary:**
Running focalboard using docker, I pulled the latest image and restart my container, but I cannot use focalboard anymore since, my sqlite database seems locked in readonly mode for some reasons

```
focalboard-focalboard | 2021/07/16 10:03:59 readConfigFile
focalboard-focalboard | 2021/07/16 10:03:59 {ServerRoot:http://localhost:8000 Port:8000 DBType:sqlite3 DBConfigString:./focalboard.db DBTablePrefix: UseSSL:false SecureCookie:false WebPath:./pack FilesDriver:local FilesS3Config:{AccessKeyID: SecretAccessKey: Bucket: PathPrefix: Region: Endpoint: SSL:false SignV2:false SSE:false Trace:false} FilesPath:./files Telemetry:true PrometheusAddress: WebhookUpdate:[] Secret: SessionExpireTime:2592000 SessionRefreshTime:18000 LocalOnly:false EnableLocalMode:true LocalModeSocketLocation:/var/tmp/focalboard_local.socket AuthMode:native LoggingCfgFile: LoggingCfgJSON: AuditCfgFile: AuditCfgJSON:}
focalboard-focalboard | info  [2021-07-16 10:03:59.071 Z] FocalBoard Server                        version=0.8.0 edition=linux build_number=dev build_date="Fri Jul 16 02:33:50 UTC 2021" build_hash=b2346fcacf82318b0df8e5d21e73c710e143c869
focalboard-focalboard | info  [2021-07-16 10:03:59.072 Z] connectDatabase                          dbType=sqlite3 connStr=./focalboard.db
focalboard-focalboard | error [2021-07-16 10:03:59.073 Z] Table creation / migration failed        error="attempt to write a readonly database in line 0: DELETE FROM schema_migrations"
focalboard-focalboard | fatal [2021-07-16 10:03:59.073 Z] server.NewStore ERROR                    error="attempt to write a readonly database in line 0: DELETE FROM schema_migrations"
focalboard-focalboard |   github.com/mattermost/logr/v2.Logger.Log
focalboard-focalboard |       /go/pkg/mod/github.com/mattermost/logr/v2@v2.0.2/logger.go"55
focalboard-focalboard |   github.com/mattermost/focalboard/server/services/mlog.(*Logger).Fatal
focalboard-focalboard |       /go/src/focalboard/server/services/mlog/mlog.go"234
focalboard-focalboard |   main.main
focalboard-focalboard |       /go/src/focalboard/server/main/main.go"165
focalboard-focalboard |
```

**Steps to reproduce the behavior:**

```
docker-compose pull
docker-compose up
```

**Expected behavior:**
The database shoudl be writeable

**Platform:**
 - Browser and version: [e.g. Chrome 88, Safari 12]
 - OS and version: [e.g. Windows, macOS 10.15.7, iOS 13.1]

**Additional context:**
The database is mounted using docker-compose and has write permissions :

```yaml
...
  focalboard:
    image: mattermost/focalboard:latest
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ".docker/config/focalboard.json:/opt/focalboard/config.json"
      - ".docker/database/focalboard.sqlite:/opt/focalboard/focalboard.db"
    user: "${UID:-1000}:${GID:-1000}"
    labels:
      - "diun.enable=true"
...
```

```
⛰  focalboard  ls -la .docker/database/focalboard.sqlite
-rwxrwxrwx 1 loranger loranger 667648 juil. 16 11:50 .docker/database/focalboard.sqlite
```

**Comment by jespino** [comment]
@loranger sorry for the late reply, it looks like somehow to a system problem, not an application problem, I would try to open a shell in the docker container and verify the permissions from the inside, probably that can give you more insights.

**Comment by loranger** [comment]
Hello @jespino 

Thanks for your reply.
I would definitely try the same, but unfortunately, there is no shell available from official focalboard image :

(from the docker-compose above)
```shell
⛰  focalboard  docker-compose run --rm focalboard sh
Creating focalboard_focalboard_run ... done
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "sh": executable file not found in $PATH: unknown
```

**Comment by loranger** [comment]
It may be related to [this issue](https://github.com/mattermost/focalboard/issues/670), but I can't figure out how I can fix it

**Comment by loranger** [comment]
I did try a clean install step-by-step using docker, docker-compose, nginx, focalboard and sqlite.

It seems the db file cannot be stored in the `/opt/focalboard/` folder anymore but *have* to be stored in `/data` path.

```yaml
...
  focalboard:
    (...)
    volumes:
      - ".docker/config/focalboard.json:/opt/focalboard/config.json"
      - ".docker/database/focalboard.sqlite:/data/focalboard.db"
...
```

The default [dbconfig](https://github.com/mattermost/focalboard/blob/main/config.json#L5) does not work anymore out of the box and have to be changed to the corresponding data path too

```json
{
    "dbtype": "sqlite3",
    "dbconfig": "/data/focalboard.db",
}
```

No more permission issue using sqlite database

**Comment by lonix1** [comment]
@loranger I tried with v0.8.2 but get same errors.

Do you maybe have a working compose file that you can share?

**Comment by loranger** [comment]
@lonix1 Sure, here is my focalboard structure:

```
focalboard
├── .docker
│   ├── config
│   │   ├── focalboard.json
│   │   └── nginx.conf
│   ├── database
│   │   ├── focalboard.sqlite
│   └── logs
│       └── nginx
├── docker-compose.yml
└── .env
```

I'm used to use `.env` files as soon as I can for my docker projects and make them more reusable, but there is nothing inside this one except a project name and an url (used by my traefik reverse proxy):

<details>
<summary>
<code>.env</code>
</summary>

```
APP_PROJECT=focalboard
APP_URL=focal.my.domain
```

</details>

[Traefik](https://traefik.io/traefik/) and [watchtower](https://containrrr.dev/watchtower/) uses labels in order to deal with the docker images:

<details>
<summary>
<code>docker-compose.yml</code>
</summary>

```yml
version: '3'

services:

  nginx:
    container_name: ${APP_PROJECT}-nginx
    image: nginx:stable-alpine
    env_file:
      - .env
    volumes:
      - ./.docker/config/nginx.conf:/etc/nginx/templates/default.conf.template
      - ./.docker/logs/nginx:/var/log/nginx
    labels:
      - "traefik.http.routers.${APP_PROJECT}.entrypoints=http"
      - "traefik.http.routers.${APP_PROJECT}.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.${APP_PROJECT}.middlewares=redirect-to-https@file"
      - "traefik.http.routers.${APP_PROJECT}-secure.entrypoints=https"
      - "traefik.http.routers.${APP_PROJECT}-secure.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.${APP_PROJECT}-secure.tls=true"
      - "traefik.http.routers.${APP_PROJECT}-secure.tls.certresolver=letsencrypt"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
    depends_on:
      - focalboard

  focalboard:
    container_name: ${APP_PROJECT}-focalboard
    image: mattermost/focalboard:latest
    # expose:
    #   - 8000
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ".docker/config/focalboard.json:/opt/focalboard/config.json"
      - ".docker/database/focalboard.sqlite:/data/focalboard.db"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    external:
      name: my-local-traefik-reversed-network

```

</details>

And in case you need them, here are my nginx (nginx template files uses [envsubst](https://hub.docker.com/_/nginx) for evaluating environment variables) and focalboard config files:

<details>
<summary>
<code>nginx.conf</code>
</summary>

```nginx
upstream focalboard-service {
   server ${APP_PROJECT}-focalboard:8000;
   keepalive 32;
}

server {
   listen 80 default_server;

   # server_name focalboard.example.com;

   location ~ /ws/* {
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       client_max_body_size 50M;
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Frame-Options SAMEORIGIN;
       proxy_buffers 256 16k;
       proxy_buffer_size 16k;
       client_body_timeout 60;
       send_timeout 300;
       lingering_timeout 5;
       proxy_connect_timeout 1d;
       proxy_send_timeout 1d;
       proxy_read_timeout 1d;
       proxy_pass http://focalboard-service;
   }

   location / {
       client_max_body_size 50M;
       proxy_set_header Connection "";
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Frame-Options SAMEORIGIN;
       proxy_buffers 256 16k;
       proxy_buffer_size 16k;
       proxy_read_timeout 600s;
       proxy_cache_revalidate on;
       proxy_cache_min_uses 2;
       proxy_cache_use_stale timeout;
       proxy_cache_lock on;
       proxy_http_version 1.1;
       proxy_pass http://focalboard-service;
   }
}

```

</details>

<details>
<summary>
<code>focalboard.json</code>
</summary>

```json
{
    "serverRoot": "http://localhost:8000",
    "port": 8000,
    "dbtype": "sqlite3",
    "dbconfig": "/data/focalboard.db",
    "postgres_dbconfig": "dbname=focalboard sslmode=disable",
    "useSSL": false,
    "webpath": "./pack",
    "filespath": "./files",
    "telemetry": true,
    "session_expire_time": 2592000,
    "session_refresh_time": 18000,
    "localOnly": false,
    "enableLocalMode": true,
    "localModeSocketLocation": "/var/tmp/focalboard_local.socket"
}

```

</details>

You may be able to make it work without nginx and using port 80 for focalboard, but maybe you are already doing it.
