### ISSUE TITLE
Bug: Websocket closed before establishing connection

### ISSUE THREAD

**Issue by Techsigns** [mattermost/focalboard#760]
**Summary:**
I've setup focalboard plugin 0.8.1 on recent Mattermost version and followed the guide under https://www.focalboard.com/download/mattermost/ to configure my Nginx reverse proxy as described. Anyway, the websocked is closed before establishing a connection, the proxy returns a 400 Bad Request

`[21/Jul/2021:09:05:41 +0000] "GET /plugins/focalboard/ws/onchange HTTP/1.1" 400 12 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"`

Mattermost is working like a charm without any issues.

my Nginx config looks like the following:

```
upstream mattermost {
    server       192.168.15.70:80; # server on another machine
    keepalive    32; # maximum number of idle keepalive connections to upstream server
}

server {
[...]
   location ~ /plugins/focalboard/ws/* {
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       client_max_body_size 50M;
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Frame-Options SAMEORIGIN;
       proxy_buffers 256 16k;
       proxy_buffer_size 16k;
       client_body_timeout 60;
       send_timeout 300;
       lingering_timeout 5;
       proxy_connect_timeout 90;
       proxy_send_timeout 300;
       proxy_read_timeout 90s;
       proxy_pass http://mattermost;
   }

 location ~ /api/v[0-9]+/(users/)?websocket$ {
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       client_max_body_size 50M;
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Frame-Options SAMEORIGIN;
       proxy_buffers 256 16k;
       proxy_buffer_size 16k;
       client_body_timeout 60;
       send_timeout 300;
       lingering_timeout 5;
       proxy_connect_timeout 90;
       proxy_send_timeout 300;
       proxy_read_timeout 90s;
       proxy_pass http://mattermost;
   }

  location / {
      proxy_pass http://mattermost;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      client_max_body_size 0;
  }
}
```

Any help is appreciated

**Comment by chenilim** [comment]
Thanks for reporting this @Techsigns! Hmmm... the config looks right, and I assume you reloaded / restarted NGINX.

Does the other machine running the server (192.168.15.70 :80) have another proxy? That's the only difference (2-machine vs. 1) in the config from what I've tried myself. Thanks.

**Comment by Techsigns** [comment]
@chenilim no, server doesn't have a proxy, it is barely a fresh Ubuntu server install with docker setup and the following docker-compose.yml to run mattermost (which works flawlessly since several months):

```
version: "3"

services:

  db:
    build: db
    read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/db/13/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost

  app:
    build:
      context: app
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
      - MM_USERNAME=XXX
      - MM_PASSWORD=XXX
      - MM_DBNAME=XXX
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@db:5432/mattermost?sslmode=disable&connect_timeout=10

  web:
    build: web
    ports:
      - "80:8080"
      - "443:8443"
    read_only: true
    restart: unless-stopped
    volumes:
      # This directory must have cert files if you want to enable SSL
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    cap_drop:
      - ALL

```
