### ISSUE TITLE
Feature: Snap / Flatpack package for Focalboard Desktop 🐧

### ISSUE THREAD

**Issue by alexanderadam** [mattermost/focalboard#79]
It would be great to have [a Snap package](https://ubuntu.com/tutorials/create-your-first-snap#3-building-a-snap-is-easy) and/or [a Flatpak package](https://docs.flatpak.org/en/latest/first-build.html) for easier installation and automatic upgrades.

**PS:** Thank you so much! Focalboard looks great! :pray:

**Comment by chenilim** [comment]
Thanks @alexanderadam! Appreciate the input. This is something we are looking into to make desktop installs easier on Linux, and perhaps for the server too. FYI @jespino.

**Comment by jespino** [comment]
Yes, I going to work on the AUR package, but would be great if somebody with Snap/Flatpack knowledge can create the packages for that.

**Comment by flandoni** [comment]
Having also AppImage package  could be convenient.

**Comment by TROMsite** [comment]
AUR would be fantastic!

**Comment by CodeCubeNeo** [comment]
Any updates on the flatpak progress?

**Comment by ankanroy-code** [comment]
Hey, I am going to seriously work on this. Any update would be nice

**Comment by skewballfox** [comment]
I'm currently trying to write up a manifest, really new to this though. I'm borrowing pretty heavily from [obsidian's unofficial flatpak](https://github.com/flathub/md.obsidian.Obsidian). 
here's what I have so far: 

```yaml
app-id: org.mattermost.Focalboard
default-branch: stable
runtime: org.gnome.Platform
runtime-version: '3.36'
sdk: org.gnome.Sdk
command:
modules:
  - name: focalboard-app
    buildsystem: simple
    build-commands:
      - mkdir -p bin share/{appdata,applications,icons/hicolor/512x512/apps}
      - mv ${FLATPAK_ID}.png         share/icons/hicolor/512x512/apps/${FLATPAK_ID}.png
      - mv ${FLATPAK_ID}.desktop     share/applications/${FLATPAK_ID}.desktop
      - mv obsidian.sh               bin/obsidian.sh
      - mv ${FLATPAK_ID}.appdata.xml share/appdata/${FLATPAK_ID}.appdata.xml
    sources:
      - type: archive
        url: https://github.com/mattermost/focalboard/releases/download/v7.7.0/focalboard-linux.tar.gz
        sha256: TODO
        only-arches: [x86_64]
```
obviously not done yet. It uses the gnome platform/sdk for the webgtk dependencies. 

Would you want to include this in the existing repo, or have it in a separate repo? Figured I'd ask before opening a draft PR.
