### ISSUE TITLE
Bug: board area half used

### ISSUE THREAD

**Issue by TOWUK** [mattermost/focalboard#815]
**Summary:**
check image
**Steps to reproduce the behavior:**
1. just create boards

**Expected behavior:**
none
**Screenshots:**
![image](https://user-images.githubusercontent.com/28830162/127767159-1f0df0b6-f199-43a7-a784-192cdea56148.png)
![image](https://user-images.githubusercontent.com/28830162/127767247-e4914f34-186e-400d-aafe-481f3705e2ef.png)

**Platform:**
 - Browser and version: latest chrome dev
 - OS and version: win11 pro 64bit

**Additional context:**
none

**Comment by kamre** [comment]
I have also noticed this [here](https://github.com/mattermost/focalboard/issues/738#issuecomment-882591170).

Propose to fix it via adding `flex` inside `centerPanel.scss`:
```scss
.focalboard-body .BoardComponent {
    ...
    > * {
        ...
        &:last-child {
            flex: 1;             // <==== add this
            padding-bottom: 8px;
        }
    }
....
```
